[package]
name = "replay"
version = "0.1.0"
edition = "2024"
authors = ["Rotem Horesh <horesh.rotem@gmail.com>"]
license = "MIT"

[dependencies]
crossterm = "0.27"
regex = "1.11"
anyhow = "1.0"
dirs = "5.0"
thiserror = "2"
# clap = { version = "4.5", features = ["derive"] }
